- CHANGES.txt
- morepath/request.py
- morepath/tests/test_path_directive.py
This keeps compatibility with webob.request.BaseRequest, where 'path' is a
property. See #292.
> Rename request.path to request.resolve_path.

- doc/superpowers.rst
- doc/views.rst
I suspect that there has been a change in the permission API which isn't fully reflected in the docs yet: I needed to write @App.permission_rule instead of just @App.permission, and pass in (identity, model, permission) instead of (model, identity).
> Magnus lycka patch permission rule

- morepath/app.py
- morepath/tests/test_mount_directive.py
- morepath/tests/test_scenario.py
- morepath/toposort.py
This is the first step in #383.
1. You now have an ``app.commit`` class method that does recursive discovery and commit of mounted apps in breadth-first order.
2. The existing tests in ``test_mount_directive`` and ``test_scenario`` use this ``app.commit()`` method instead of ``dectate.commit()``
3. Added a specific test to ensure that breadth-first order is compatible with a rather convoluted inheritance and mounting graph.
> Recursive commit

- morepath/app.py
- morepath/tests/test_config_logging.py
- morepath/tests/test_defer_links.py
- morepath/tests/test_directive.py
- morepath/tests/test_excview.py
- morepath/tests/test_extend.py
- morepath/tests/test_implicit.py
- morepath/tests/test_internal.py
- morepath/tests/test_json_obj.py
- morepath/tests/test_mount_directive.py
- morepath/tests/test_path_directive.py
- morepath/tests/test_predicate.py
- morepath/tests/test_predicates.py
- morepath/tests/test_scenario.py
- morepath/tests/test_security.py
- morepath/tests/test_template.py
- morepath/tests/test_tween.py
- morepath/tests/test_view_directive.py
This addresses #392.
- The check on whether the app is committed and automatic commit is carried out inside the reification of app.lookup, so it is outside the critical path of WSGI serving.
- If and when automatic commit takes place is examined in detail using config logging.
- Most of the tests with the following pattern have been modified by taking out dectate.commit:
```
dectate.commit(app,...)
c = Client(app())
c.get(...)
```
- Similarly for tests with the following pattern:
```
dectate.commit(app,...)
a = app()
...a.lookup...
```
- A few additional tests have been slightly reformulated.
> Auto-commit an application upon the first WSGI request

- doc/conf.py
- doc/paths_and_linking.rst
First step towards the introduction of doctests in the morepath documentation:
* No new documentation here. Only adding tests to the existing docs.
* sphinx.ext.doctest has [hard-coded defaults for the flags](https://github.com/sphinx-doc/sphinx/issues/2471) which are different from the default flags in the standard library.  If you want to catch the small diff in the exception detail (the string format) you need extra flags.
> Using doctests in the docs.

- buildout.cfg
- doc/building_large_applications.rst
- doc/code_examples/hello.py
- doc/conf.py
- doc/developing.rst
- doc/installation.rst
- doc/quickstart.rst
- doc/testing.rst
- doc/toc.rst
- As discussed in #203.
- Doctest tests the test used as example and the line-by-line walkthrough.
- Added intersphinx setup for webtest.
- Also mention `(cd doc/build; make doctest)` in the instructions on how to run doctests.
> Added initial doc for automated tests

- morepath/app.py
- morepath/autosetup.py
- morepath/error.py
- morepath/tests/test_autosetup.py
- morepath/tests/test_scanning.py
This addresses #405:
1. The function ``autosetup`` no longer invokes ``autocommit`` and now issues a deprecation warning.
2. The docstring of ``autosetup`` has a ``**Deprecated**`` notice.
3. The testing of ``autosetup`` has been updated.
4. References to ``autosetup`` and ``autocommit`` in docstrings have been updated.
The only remaining references to ``autosetup`` and ``autocommit`` in the code are:
1. The test of ``autosetup`` itself.
2. Publising in ``morepath/__init__.py``.
Sill to do:
* Remove ``autosetup`` and ``autocommit`` from the narrative docs.
* Marking the deprecation in CHANGES.txt.
> Phasing out autosetup

- doc/code_examples/hello.py
- doc/quickstart.rst
This addresses #406:
* ``autocommit`` is removed from the "hello world" app.
* Point 6 from the code walkthrough is removed.
* Minor adjustments to a few other code examples.
> Update the quickstart

- morepath/reify.py
- morepath/tests/test_reify.py
1. Removed unnecessary (and untestable) try-except clause from reify, as all Python objects have a `__doc__` descriptor.
2. Testing the docstring.
3. Have consistent indentation in the docstring.
4. Removed the "flake8: noqa" flag from reify.
> Cleanup of reify

- doc/app_reuse.rst
`WikiApp` had become `wiki_app` and simply `App` in the decorators.
> Fixed app class name in WikiApp example.

- doc/quickstart.rst
- morepath/run.py
- morepath/tests/conftest.py
- morepath/tests/test_run.py
This follows up on the discussion in #439:
* Added command-line parsing to ``morepath.run``. 
* Added tests for ``morepath.run``, which has now a richer behavior.
* The quickstart guide now mentions the possibility of specifying arguments on the command line.
Here is the new signature:
<dl class="function">
<dt id="morepath.run">
<code>morepath.run</code><span class="sig-paren">(</span><em>wsgi</em>, <em>host='127.0.0.1'</em>, <em>port=5000</em>, <em>prog=None</em>, <em>ignore_cli=False</em>, <em>callback=None</em><span class="sig-paren">)</span><a class="headerlink" href="#morepath.run" title="Permalink to this definition">¶</a></dt>
<dd><p>Uses wsgiref.simple_server to run an application for debugging purposes.</p>
<p>Under non-exceptional circumstances this function never returns.</p> …
> Added command line parsing to morepath.run

- doc/api.rst
> Provide sphinx with an explicit signature when introspection fails.

- morepath/tests/test_autosetup.py
When running the test suite of Morepath together with that of any of the extensions,  ``morepath_packages()`` will include those extensions too, so an equality test with a subset of the fixture packages will fail.
This Pull Request addresses that issue.
> Improved test isolation.

- CHANGES.txt
- morepath/core.py
In core.py was used `# flake8: noqa`, which prevented the whole file to be tested by flake8.
I changed this to `# noqa` which ignores only the specific line.
As a result I got many unused imports errors:
```python
import dectate
import importscan
from webob import Response as BaseResponse, BaseRequest
from . import directive  # install directives with App
from .view import View
from .request import Request, Response
```
I made flake8 ignore the `dectate` and `directive` import as they seem to be necessary and removed the other ones. I also fixed some minor flake8 warnings.
@faassen  Please check if this is ok or if I have removed to much imports. The tests are all passing.
This PR was split of PR #456.
> Remove unused imports and fix pep8 in core.py

- doc/advanced-topics.rst
- doc/api-reference.rst
- doc/conf.py
- doc/contributor-guide.rst
- doc/getting-started.rst
- doc/project-history.rst
- doc/toc.rst
- doc/user-guide.rst
I actually got around to reorganizing the TOC into a hierarchical structure. It can be previewed as:
* http://taschini-morepath.readthedocs.io
The Latex-generated PDF file is structured accordingly.
> Reorganized the TOC of the docs into a hierarchy

- .travis.yml
- .travis_tox.ini
- CHANGES.txt
- morepath/tests/test_mount_directive.py
- setup.py
- tox.ini
Use travis-tox for compatibility with Pypy
Remove 3.3 as it's unsupported by pytest
Add 3.6 to tox
Fix PEP8 violation in tests
> Travis CI 3.6

- doc/organizing_your_project.rst
I encountered a broken link while browsing the tutorial. I think it should point to http://setuptools.readthedocs.io.
> Fix link to namespace packages documentation

- doc/index.rst
RTD delivers content via https, the embedded YouTube video was linked via http.
As a result modern browsers such as Chrome or Firefox did not show the embedded video.
> Fix mixed content type error.

- morepath/tests/fixtures/config/settings.py
... and thus make Travis go green for all build jobs.
modified:   morepath/tests/fixtures/config/settings.py
> Fix PEP 8 in settings.py

- doc/json.rst
- doc/web.rst
- morepath/app.py
- morepath/autosetup.py
- morepath/tests/test_excview.py
- morepath/tests/test_request.py
- morepath/tests/test_run.py
- morepath/tests/test_security.py
There are small typos in:
- doc/json.rst
- doc/web.rst
- morepath/app.py
- morepath/autosetup.py
- morepath/tests/test_excview.py
- morepath/tests/test_request.py
- morepath/tests/test_run.py
- morepath/tests/test_security.py
Fixes:
- Should read `verified` rather than `verfied`.
- Should read `successfully` rather than `succesfully`.
- Should read `parameters` rather than `paramaters`.
- Should read `omitted` rather than `ommitted`.
- Should read `instance` rather than `istance`.
- Should read `influence` rather than `infleunce`.
- Should read `including` rather than `incuding`.
- Should read `gracefully` rather than `gracefuly`.
Closes #551
> docs: fix a few simple typos
