- doc/views.rst
Those function signatures have changed in 0.7
> Update the out of date render docs

- buildout.cfg
> Remove prospector from development dependencies.

- morepath/directive.py
- morepath/tests/test_security.py
> Add settings as an optional argument to the identity_policy directive.

- doc/security.rst
- morepath/tests/test_security.py
> Add documention for using settings in the identity policy.

- doc/building_large_applications.rst
- doc/more.static.rst
- doc/organizing_your_project.rst
> Documentation improvement for Issue 345

- CHANGES.txt
- morepath/app.py
- morepath/tests/test_setting_directive.py
>  Brings app.settings back

- morepath/tests/test_config_logging.py
- morepath/tests/test_directive.py
- morepath/tests/test_error.py
- morepath/tests/test_scanning.py
- morepath/tests/test_security.py
- morepath/tests/test_template.py
> Removed redundant scans in test suite.

- morepath/tests/test_directive.py
Part of the discussion in #378.
> Added test for the instantiate-configure-commit use case

- morepath/run.py
> Friendlier morepath.run

- morepath/error.py
- morepath/toposort.py
> Use topological_sort from dectate (#403)

- doc/api.rst
- morepath/__init__.py
- morepath/app.py
- morepath/autosetup.py
- morepath/tests/test_autosetup.py
> Remove deprecated autosetup

- doc/quickstart.rst
A little step to increase doctest coverage of the docs.
> Doctest linking to models in doc/quickstart.rst

- doc/views.rst
> Fixed typo mentioned in #424.

- morepath/tests/test_path_directive.py
> Recast xfail test following decision to reject #155.

- bootstrap.py
The version of `bootstrap.py` currently in the Morepath repository triggers this warning:
```
.../site-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have
iterated over the result of pkg_resources.parse_version. This is a legacy
behavior which is inconsistent with the new version class introduced in
setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For
comparison of versions, sort the Version instances directly. If you have
another use case requiring the tuple, please file a bug with the setuptools
project describing that need.
```
The new version no longer does that.
> Updated boostrap.py to version '2015-07-01'

- CHANGES.txt
- doc/security.rst
- doc/settings.rst
- morepath/app.py
- morepath/authentication.py
- morepath/directive.py
- morepath/generic.py
- morepath/tests/test_security.py
- morepath/tests/test_setting_directive.py
This is work in progress towards #446.
> Added forget_identity and remember_identity methods to morepath.App.

- CHANGES.txt
- morepath/__init__.py
- morepath/implicit.py
- morepath/tests/test_autosetup.py
> Deprecated morepath.enable_implicit, morepath.disable_implicit.

- .travis.yml
- CHANGES.txt
- doc/developing.rst
- doc/installation.rst
- doc/settings.rst
- doc/testing.rst
- morepath/compat.py
- morepath/core.py
- morepath/path.py
- morepath/reify.py
- setup.py
- tox.ini
I'm going here consequently one step further then planned and proposing to make Python 3.5 the default Python environment.
> Make Python 3.5 the default Python environment.

- CHANGES.txt
- develop_requirements.txt
- morepath/app.py
- morepath/core.py
- morepath/directive.py
- morepath/tween.py
This updates Morepath as per this change in Dectate: 
https://github.com/morepath/dectate/pull/40
> No more directive directive

- CHANGES.txt
- morepath/app.py
- morepath/request.py
- morepath/tests/test_directive.py
> Fixes link prefix not applying to mounted applications.

- morepath/core.py
Inspired by this change: https://github.com/django/django/commit/77b06e41516d8136b56c040cba7e235b
Fixes issue #522
> Fix issue #522

- doc/building_large_applications.rst
I believe this was a mistake? Great docs btw 💯
> Fix reference to Wiki on Issue segment.

- CHANGES.txt
> Add changelog entries
